import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

type Film = {
  createdDate: string;
  filmId: string;
  imgUrl: string;
  title: string;
}

type HomeProps = {
  data: Array<Film>
}

const Home: NextPage<HomeProps> = ({ data }) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>
          {data.map(item => (
            <a href="#" className={styles.card} key={item.filmId}>
              <h2>{item.title} &rarr;</h2>
              <Image height={300} width={300} src={item.imgUrl?.split("?")?.[0]} alt={item.title} />
              <p>{item.createdDate}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export async function getServerSideProps() {
  const jsonData = await fetch(process.env.NODE_ENV === 'development' ? "http://localhost:3000/films" : "https://nest-project-production.up.railway.app/films")
  const data: Array<Film> = await jsonData.json();
  return { props: { data } }
}

export default Home
